package com.ezhuanbing.api.dao.mybatis.mapper;

import com.ezhuanbing.api.dao.mybatis.model.ContentClassTemplates;
import com.ezhuanbing.api.dao.mybatis.model.ContentClassTemplatesCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContentClassTemplatesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    int countByExample(ContentClassTemplatesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    int deleteByExample(ContentClassTemplatesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    int insert(ContentClassTemplates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    int insertSelective(ContentClassTemplates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    List<ContentClassTemplates> selectByExample(ContentClassTemplatesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    ContentClassTemplates selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    int updateByExampleSelective(@Param("record") ContentClassTemplates record, @Param("example") ContentClassTemplatesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    int updateByExample(@Param("record") ContentClassTemplates record, @Param("example") ContentClassTemplatesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    int updateByPrimaryKeySelective(ContentClassTemplates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    int updateByPrimaryKey(ContentClassTemplates record);
}