package com.ezhuanbing.api.dao.mybatis.mapper;

import com.ezhuanbing.api.dao.mybatis.model.EducationFile;
import com.ezhuanbing.api.dao.mybatis.model.EducationFileCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EducationFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_educationfile
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    int countByExample(EducationFileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_educationfile
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    int deleteByExample(EducationFileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_educationfile
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_educationfile
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    int insert(EducationFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_educationfile
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    int insertSelective(EducationFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_educationfile
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    List<EducationFile> selectByExample(EducationFileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_educationfile
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    EducationFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_educationfile
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    int updateByExampleSelective(@Param("record") EducationFile record, @Param("example") EducationFileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_educationfile
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    int updateByExample(@Param("record") EducationFile record, @Param("example") EducationFileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_educationfile
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    int updateByPrimaryKeySelective(EducationFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_educationfile
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    int updateByPrimaryKey(EducationFile record);
}