package com.ezhuanbing.api.dao.mybatis.mapper;

import com.ezhuanbing.api.dao.mybatis.model.OptionTemplates;
import com.ezhuanbing.api.dao.mybatis.model.OptionTemplatesCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OptionTemplatesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    int countByExample(OptionTemplatesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    int deleteByExample(OptionTemplatesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    int insert(OptionTemplates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    int insertSelective(OptionTemplates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    List<OptionTemplates> selectByExampleWithBLOBs(OptionTemplatesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    List<OptionTemplates> selectByExample(OptionTemplatesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    OptionTemplates selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    int updateByExampleSelective(@Param("record") OptionTemplates record, @Param("example") OptionTemplatesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") OptionTemplates record, @Param("example") OptionTemplatesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    int updateByExample(@Param("record") OptionTemplates record, @Param("example") OptionTemplatesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    int updateByPrimaryKeySelective(OptionTemplates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(OptionTemplates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    int updateByPrimaryKey(OptionTemplates record);
}