package com.ezhuanbing.api.dao.mybatis.mapper;

import com.ezhuanbing.api.dao.mybatis.model.PapersTemplates;
import com.ezhuanbing.api.dao.mybatis.model.PapersTemplatesCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PapersTemplatesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    int countByExample(PapersTemplatesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    int deleteByExample(PapersTemplatesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    int insert(PapersTemplates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    int insertSelective(PapersTemplates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    List<PapersTemplates> selectByExample(PapersTemplatesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    PapersTemplates selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    int updateByExampleSelective(@Param("record") PapersTemplates record, @Param("example") PapersTemplatesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    int updateByExample(@Param("record") PapersTemplates record, @Param("example") PapersTemplatesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    int updateByPrimaryKeySelective(PapersTemplates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    int updateByPrimaryKey(PapersTemplates record);
}