package com.ezhuanbing.api.dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ChatRecordCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_chatrecord
     *
     * @mbggenerated Sat Oct 15 13:56:30 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_chatrecord
     *
     * @mbggenerated Sat Oct 15 13:56:30 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_chatrecord
     *
     * @mbggenerated Sat Oct 15 13:56:30 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_chatrecord
     *
     * @mbggenerated Sat Oct 15 13:56:30 CST 2016
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_chatrecord
     *
     * @mbggenerated Sat Oct 15 13:56:30 CST 2016
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_chatrecord
     *
     * @mbggenerated Sat Oct 15 13:56:30 CST 2016
     */
    public ChatRecordCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_chatrecord
     *
     * @mbggenerated Sat Oct 15 13:56:30 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_chatrecord
     *
     * @mbggenerated Sat Oct 15 13:56:30 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_chatrecord
     *
     * @mbggenerated Sat Oct 15 13:56:30 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_chatrecord
     *
     * @mbggenerated Sat Oct 15 13:56:30 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_chatrecord
     *
     * @mbggenerated Sat Oct 15 13:56:30 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_chatrecord
     *
     * @mbggenerated Sat Oct 15 13:56:30 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_chatrecord
     *
     * @mbggenerated Sat Oct 15 13:56:30 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_chatrecord
     *
     * @mbggenerated Sat Oct 15 13:56:30 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_chatrecord
     *
     * @mbggenerated Sat Oct 15 13:56:30 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_chatrecord
     *
     * @mbggenerated Sat Oct 15 13:56:30 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_chatrecord
     *
     * @mbggenerated Sat Oct 15 13:56:30 CST 2016
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_chatrecord
     *
     * @mbggenerated Sat Oct 15 13:56:30 CST 2016
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_chatrecord
     *
     * @mbggenerated Sat Oct 15 13:56:30 CST 2016
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_chatrecord
     *
     * @mbggenerated Sat Oct 15 13:56:30 CST 2016
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mb_chatrecord
     *
     * @mbggenerated Sat Oct 15 13:56:30 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPlandetailidIsNull() {
            addCriterion("planDetailId is null");
            return (Criteria) this;
        }

        public Criteria andPlandetailidIsNotNull() {
            addCriterion("planDetailId is not null");
            return (Criteria) this;
        }

        public Criteria andPlandetailidEqualTo(Integer value) {
            addCriterion("planDetailId =", value, "plandetailid");
            return (Criteria) this;
        }

        public Criteria andPlandetailidNotEqualTo(Integer value) {
            addCriterion("planDetailId <>", value, "plandetailid");
            return (Criteria) this;
        }

        public Criteria andPlandetailidGreaterThan(Integer value) {
            addCriterion("planDetailId >", value, "plandetailid");
            return (Criteria) this;
        }

        public Criteria andPlandetailidGreaterThanOrEqualTo(Integer value) {
            addCriterion("planDetailId >=", value, "plandetailid");
            return (Criteria) this;
        }

        public Criteria andPlandetailidLessThan(Integer value) {
            addCriterion("planDetailId <", value, "plandetailid");
            return (Criteria) this;
        }

        public Criteria andPlandetailidLessThanOrEqualTo(Integer value) {
            addCriterion("planDetailId <=", value, "plandetailid");
            return (Criteria) this;
        }

        public Criteria andPlandetailidIn(List<Integer> values) {
            addCriterion("planDetailId in", values, "plandetailid");
            return (Criteria) this;
        }

        public Criteria andPlandetailidNotIn(List<Integer> values) {
            addCriterion("planDetailId not in", values, "plandetailid");
            return (Criteria) this;
        }

        public Criteria andPlandetailidBetween(Integer value1, Integer value2) {
            addCriterion("planDetailId between", value1, value2, "plandetailid");
            return (Criteria) this;
        }

        public Criteria andPlandetailidNotBetween(Integer value1, Integer value2) {
            addCriterion("planDetailId not between", value1, value2, "plandetailid");
            return (Criteria) this;
        }

        public Criteria andChatpersonidIsNull() {
            addCriterion("chatPersonId is null");
            return (Criteria) this;
        }

        public Criteria andChatpersonidIsNotNull() {
            addCriterion("chatPersonId is not null");
            return (Criteria) this;
        }

        public Criteria andChatpersonidEqualTo(String value) {
            addCriterion("chatPersonId =", value, "chatpersonid");
            return (Criteria) this;
        }

        public Criteria andChatpersonidNotEqualTo(String value) {
            addCriterion("chatPersonId <>", value, "chatpersonid");
            return (Criteria) this;
        }

        public Criteria andChatpersonidGreaterThan(String value) {
            addCriterion("chatPersonId >", value, "chatpersonid");
            return (Criteria) this;
        }

        public Criteria andChatpersonidGreaterThanOrEqualTo(String value) {
            addCriterion("chatPersonId >=", value, "chatpersonid");
            return (Criteria) this;
        }

        public Criteria andChatpersonidLessThan(String value) {
            addCriterion("chatPersonId <", value, "chatpersonid");
            return (Criteria) this;
        }

        public Criteria andChatpersonidLessThanOrEqualTo(String value) {
            addCriterion("chatPersonId <=", value, "chatpersonid");
            return (Criteria) this;
        }

        public Criteria andChatpersonidLike(String value) {
            addCriterion("chatPersonId like", value, "chatpersonid");
            return (Criteria) this;
        }

        public Criteria andChatpersonidNotLike(String value) {
            addCriterion("chatPersonId not like", value, "chatpersonid");
            return (Criteria) this;
        }

        public Criteria andChatpersonidIn(List<String> values) {
            addCriterion("chatPersonId in", values, "chatpersonid");
            return (Criteria) this;
        }

        public Criteria andChatpersonidNotIn(List<String> values) {
            addCriterion("chatPersonId not in", values, "chatpersonid");
            return (Criteria) this;
        }

        public Criteria andChatpersonidBetween(String value1, String value2) {
            addCriterion("chatPersonId between", value1, value2, "chatpersonid");
            return (Criteria) this;
        }

        public Criteria andChatpersonidNotBetween(String value1, String value2) {
            addCriterion("chatPersonId not between", value1, value2, "chatpersonid");
            return (Criteria) this;
        }

        public Criteria andChatpersonnameIsNull() {
            addCriterion("chatPersonName is null");
            return (Criteria) this;
        }

        public Criteria andChatpersonnameIsNotNull() {
            addCriterion("chatPersonName is not null");
            return (Criteria) this;
        }

        public Criteria andChatpersonnameEqualTo(String value) {
            addCriterion("chatPersonName =", value, "chatpersonname");
            return (Criteria) this;
        }

        public Criteria andChatpersonnameNotEqualTo(String value) {
            addCriterion("chatPersonName <>", value, "chatpersonname");
            return (Criteria) this;
        }

        public Criteria andChatpersonnameGreaterThan(String value) {
            addCriterion("chatPersonName >", value, "chatpersonname");
            return (Criteria) this;
        }

        public Criteria andChatpersonnameGreaterThanOrEqualTo(String value) {
            addCriterion("chatPersonName >=", value, "chatpersonname");
            return (Criteria) this;
        }

        public Criteria andChatpersonnameLessThan(String value) {
            addCriterion("chatPersonName <", value, "chatpersonname");
            return (Criteria) this;
        }

        public Criteria andChatpersonnameLessThanOrEqualTo(String value) {
            addCriterion("chatPersonName <=", value, "chatpersonname");
            return (Criteria) this;
        }

        public Criteria andChatpersonnameLike(String value) {
            addCriterion("chatPersonName like", value, "chatpersonname");
            return (Criteria) this;
        }

        public Criteria andChatpersonnameNotLike(String value) {
            addCriterion("chatPersonName not like", value, "chatpersonname");
            return (Criteria) this;
        }

        public Criteria andChatpersonnameIn(List<String> values) {
            addCriterion("chatPersonName in", values, "chatpersonname");
            return (Criteria) this;
        }

        public Criteria andChatpersonnameNotIn(List<String> values) {
            addCriterion("chatPersonName not in", values, "chatpersonname");
            return (Criteria) this;
        }

        public Criteria andChatpersonnameBetween(String value1, String value2) {
            addCriterion("chatPersonName between", value1, value2, "chatpersonname");
            return (Criteria) this;
        }

        public Criteria andChatpersonnameNotBetween(String value1, String value2) {
            addCriterion("chatPersonName not between", value1, value2, "chatpersonname");
            return (Criteria) this;
        }

        public Criteria andChatpersonimageIsNull() {
            addCriterion("chatPersonImage is null");
            return (Criteria) this;
        }

        public Criteria andChatpersonimageIsNotNull() {
            addCriterion("chatPersonImage is not null");
            return (Criteria) this;
        }

        public Criteria andChatpersonimageEqualTo(String value) {
            addCriterion("chatPersonImage =", value, "chatpersonimage");
            return (Criteria) this;
        }

        public Criteria andChatpersonimageNotEqualTo(String value) {
            addCriterion("chatPersonImage <>", value, "chatpersonimage");
            return (Criteria) this;
        }

        public Criteria andChatpersonimageGreaterThan(String value) {
            addCriterion("chatPersonImage >", value, "chatpersonimage");
            return (Criteria) this;
        }

        public Criteria andChatpersonimageGreaterThanOrEqualTo(String value) {
            addCriterion("chatPersonImage >=", value, "chatpersonimage");
            return (Criteria) this;
        }

        public Criteria andChatpersonimageLessThan(String value) {
            addCriterion("chatPersonImage <", value, "chatpersonimage");
            return (Criteria) this;
        }

        public Criteria andChatpersonimageLessThanOrEqualTo(String value) {
            addCriterion("chatPersonImage <=", value, "chatpersonimage");
            return (Criteria) this;
        }

        public Criteria andChatpersonimageLike(String value) {
            addCriterion("chatPersonImage like", value, "chatpersonimage");
            return (Criteria) this;
        }

        public Criteria andChatpersonimageNotLike(String value) {
            addCriterion("chatPersonImage not like", value, "chatpersonimage");
            return (Criteria) this;
        }

        public Criteria andChatpersonimageIn(List<String> values) {
            addCriterion("chatPersonImage in", values, "chatpersonimage");
            return (Criteria) this;
        }

        public Criteria andChatpersonimageNotIn(List<String> values) {
            addCriterion("chatPersonImage not in", values, "chatpersonimage");
            return (Criteria) this;
        }

        public Criteria andChatpersonimageBetween(String value1, String value2) {
            addCriterion("chatPersonImage between", value1, value2, "chatpersonimage");
            return (Criteria) this;
        }

        public Criteria andChatpersonimageNotBetween(String value1, String value2) {
            addCriterion("chatPersonImage not between", value1, value2, "chatpersonimage");
            return (Criteria) this;
        }

        public Criteria andChatdatetimeIsNull() {
            addCriterion("chatDateTime is null");
            return (Criteria) this;
        }

        public Criteria andChatdatetimeIsNotNull() {
            addCriterion("chatDateTime is not null");
            return (Criteria) this;
        }

        public Criteria andChatdatetimeEqualTo(Date value) {
            addCriterion("chatDateTime =", value, "chatdatetime");
            return (Criteria) this;
        }

        public Criteria andChatdatetimeNotEqualTo(Date value) {
            addCriterion("chatDateTime <>", value, "chatdatetime");
            return (Criteria) this;
        }

        public Criteria andChatdatetimeGreaterThan(Date value) {
            addCriterion("chatDateTime >", value, "chatdatetime");
            return (Criteria) this;
        }

        public Criteria andChatdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("chatDateTime >=", value, "chatdatetime");
            return (Criteria) this;
        }

        public Criteria andChatdatetimeLessThan(Date value) {
            addCriterion("chatDateTime <", value, "chatdatetime");
            return (Criteria) this;
        }

        public Criteria andChatdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("chatDateTime <=", value, "chatdatetime");
            return (Criteria) this;
        }

        public Criteria andChatdatetimeIn(List<Date> values) {
            addCriterion("chatDateTime in", values, "chatdatetime");
            return (Criteria) this;
        }

        public Criteria andChatdatetimeNotIn(List<Date> values) {
            addCriterion("chatDateTime not in", values, "chatdatetime");
            return (Criteria) this;
        }

        public Criteria andChatdatetimeBetween(Date value1, Date value2) {
            addCriterion("chatDateTime between", value1, value2, "chatdatetime");
            return (Criteria) this;
        }

        public Criteria andChatdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("chatDateTime not between", value1, value2, "chatdatetime");
            return (Criteria) this;
        }

        public Criteria andChattargetIsNull() {
            addCriterion("chatTarget is null");
            return (Criteria) this;
        }

        public Criteria andChattargetIsNotNull() {
            addCriterion("chatTarget is not null");
            return (Criteria) this;
        }

        public Criteria andChattargetEqualTo(Integer value) {
            addCriterion("chatTarget =", value, "chattarget");
            return (Criteria) this;
        }

        public Criteria andChattargetNotEqualTo(Integer value) {
            addCriterion("chatTarget <>", value, "chattarget");
            return (Criteria) this;
        }

        public Criteria andChattargetGreaterThan(Integer value) {
            addCriterion("chatTarget >", value, "chattarget");
            return (Criteria) this;
        }

        public Criteria andChattargetGreaterThanOrEqualTo(Integer value) {
            addCriterion("chatTarget >=", value, "chattarget");
            return (Criteria) this;
        }

        public Criteria andChattargetLessThan(Integer value) {
            addCriterion("chatTarget <", value, "chattarget");
            return (Criteria) this;
        }

        public Criteria andChattargetLessThanOrEqualTo(Integer value) {
            addCriterion("chatTarget <=", value, "chattarget");
            return (Criteria) this;
        }

        public Criteria andChattargetIn(List<Integer> values) {
            addCriterion("chatTarget in", values, "chattarget");
            return (Criteria) this;
        }

        public Criteria andChattargetNotIn(List<Integer> values) {
            addCriterion("chatTarget not in", values, "chattarget");
            return (Criteria) this;
        }

        public Criteria andChattargetBetween(Integer value1, Integer value2) {
            addCriterion("chatTarget between", value1, value2, "chattarget");
            return (Criteria) this;
        }

        public Criteria andChattargetNotBetween(Integer value1, Integer value2) {
            addCriterion("chatTarget not between", value1, value2, "chattarget");
            return (Criteria) this;
        }

        public Criteria andContenttypeIsNull() {
            addCriterion("contentType is null");
            return (Criteria) this;
        }

        public Criteria andContenttypeIsNotNull() {
            addCriterion("contentType is not null");
            return (Criteria) this;
        }

        public Criteria andContenttypeEqualTo(String value) {
            addCriterion("contentType =", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeNotEqualTo(String value) {
            addCriterion("contentType <>", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeGreaterThan(String value) {
            addCriterion("contentType >", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeGreaterThanOrEqualTo(String value) {
            addCriterion("contentType >=", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeLessThan(String value) {
            addCriterion("contentType <", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeLessThanOrEqualTo(String value) {
            addCriterion("contentType <=", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeLike(String value) {
            addCriterion("contentType like", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeNotLike(String value) {
            addCriterion("contentType not like", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeIn(List<String> values) {
            addCriterion("contentType in", values, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeNotIn(List<String> values) {
            addCriterion("contentType not in", values, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeBetween(String value1, String value2) {
            addCriterion("contentType between", value1, value2, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeNotBetween(String value1, String value2) {
            addCriterion("contentType not between", value1, value2, "contenttype");
            return (Criteria) this;
        }

        public Criteria andIsdoctormsgIsNull() {
            addCriterion("isDoctorMsg is null");
            return (Criteria) this;
        }

        public Criteria andIsdoctormsgIsNotNull() {
            addCriterion("isDoctorMsg is not null");
            return (Criteria) this;
        }

        public Criteria andIsdoctormsgEqualTo(String value) {
            addCriterion("isDoctorMsg =", value, "isdoctormsg");
            return (Criteria) this;
        }

        public Criteria andIsdoctormsgNotEqualTo(String value) {
            addCriterion("isDoctorMsg <>", value, "isdoctormsg");
            return (Criteria) this;
        }

        public Criteria andIsdoctormsgGreaterThan(String value) {
            addCriterion("isDoctorMsg >", value, "isdoctormsg");
            return (Criteria) this;
        }

        public Criteria andIsdoctormsgGreaterThanOrEqualTo(String value) {
            addCriterion("isDoctorMsg >=", value, "isdoctormsg");
            return (Criteria) this;
        }

        public Criteria andIsdoctormsgLessThan(String value) {
            addCriterion("isDoctorMsg <", value, "isdoctormsg");
            return (Criteria) this;
        }

        public Criteria andIsdoctormsgLessThanOrEqualTo(String value) {
            addCriterion("isDoctorMsg <=", value, "isdoctormsg");
            return (Criteria) this;
        }

        public Criteria andIsdoctormsgLike(String value) {
            addCriterion("isDoctorMsg like", value, "isdoctormsg");
            return (Criteria) this;
        }

        public Criteria andIsdoctormsgNotLike(String value) {
            addCriterion("isDoctorMsg not like", value, "isdoctormsg");
            return (Criteria) this;
        }

        public Criteria andIsdoctormsgIn(List<String> values) {
            addCriterion("isDoctorMsg in", values, "isdoctormsg");
            return (Criteria) this;
        }

        public Criteria andIsdoctormsgNotIn(List<String> values) {
            addCriterion("isDoctorMsg not in", values, "isdoctormsg");
            return (Criteria) this;
        }

        public Criteria andIsdoctormsgBetween(String value1, String value2) {
            addCriterion("isDoctorMsg between", value1, value2, "isdoctormsg");
            return (Criteria) this;
        }

        public Criteria andIsdoctormsgNotBetween(String value1, String value2) {
            addCriterion("isDoctorMsg not between", value1, value2, "isdoctormsg");
            return (Criteria) this;
        }

        public Criteria andPconlineIsNull() {
            addCriterion("pcOnline is null");
            return (Criteria) this;
        }

        public Criteria andPconlineIsNotNull() {
            addCriterion("pcOnline is not null");
            return (Criteria) this;
        }

        public Criteria andPconlineEqualTo(String value) {
            addCriterion("pcOnline =", value, "pconline");
            return (Criteria) this;
        }

        public Criteria andPconlineNotEqualTo(String value) {
            addCriterion("pcOnline <>", value, "pconline");
            return (Criteria) this;
        }

        public Criteria andPconlineGreaterThan(String value) {
            addCriterion("pcOnline >", value, "pconline");
            return (Criteria) this;
        }

        public Criteria andPconlineGreaterThanOrEqualTo(String value) {
            addCriterion("pcOnline >=", value, "pconline");
            return (Criteria) this;
        }

        public Criteria andPconlineLessThan(String value) {
            addCriterion("pcOnline <", value, "pconline");
            return (Criteria) this;
        }

        public Criteria andPconlineLessThanOrEqualTo(String value) {
            addCriterion("pcOnline <=", value, "pconline");
            return (Criteria) this;
        }

        public Criteria andPconlineLike(String value) {
            addCriterion("pcOnline like", value, "pconline");
            return (Criteria) this;
        }

        public Criteria andPconlineNotLike(String value) {
            addCriterion("pcOnline not like", value, "pconline");
            return (Criteria) this;
        }

        public Criteria andPconlineIn(List<String> values) {
            addCriterion("pcOnline in", values, "pconline");
            return (Criteria) this;
        }

        public Criteria andPconlineNotIn(List<String> values) {
            addCriterion("pcOnline not in", values, "pconline");
            return (Criteria) this;
        }

        public Criteria andPconlineBetween(String value1, String value2) {
            addCriterion("pcOnline between", value1, value2, "pconline");
            return (Criteria) this;
        }

        public Criteria andPconlineNotBetween(String value1, String value2) {
            addCriterion("pcOnline not between", value1, value2, "pconline");
            return (Criteria) this;
        }

        public Criteria andChatpersonidLikeInsensitive(String value) {
            addCriterion("upper(chatPersonId) like", value.toUpperCase(), "chatpersonid");
            return (Criteria) this;
        }

        public Criteria andChatpersonnameLikeInsensitive(String value) {
            addCriterion("upper(chatPersonName) like", value.toUpperCase(), "chatpersonname");
            return (Criteria) this;
        }

        public Criteria andChatpersonimageLikeInsensitive(String value) {
            addCriterion("upper(chatPersonImage) like", value.toUpperCase(), "chatpersonimage");
            return (Criteria) this;
        }

        public Criteria andContenttypeLikeInsensitive(String value) {
            addCriterion("upper(contentType) like", value.toUpperCase(), "contenttype");
            return (Criteria) this;
        }

        public Criteria andIsdoctormsgLikeInsensitive(String value) {
            addCriterion("upper(isDoctorMsg) like", value.toUpperCase(), "isdoctormsg");
            return (Criteria) this;
        }

        public Criteria andPconlineLikeInsensitive(String value) {
            addCriterion("upper(pcOnline) like", value.toUpperCase(), "pconline");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mb_chatrecord
     *
     * @mbggenerated do_not_delete_during_merge Sat Oct 15 13:56:30 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mb_chatrecord
     *
     * @mbggenerated Sat Oct 15 13:56:30 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}