package com.ezhuanbing.api.dao.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class ContentClassTemplatesCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    public ContentClassTemplatesCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPapersidIsNull() {
            addCriterion("papersId is null");
            return (Criteria) this;
        }

        public Criteria andPapersidIsNotNull() {
            addCriterion("papersId is not null");
            return (Criteria) this;
        }

        public Criteria andPapersidEqualTo(Integer value) {
            addCriterion("papersId =", value, "papersid");
            return (Criteria) this;
        }

        public Criteria andPapersidNotEqualTo(Integer value) {
            addCriterion("papersId <>", value, "papersid");
            return (Criteria) this;
        }

        public Criteria andPapersidGreaterThan(Integer value) {
            addCriterion("papersId >", value, "papersid");
            return (Criteria) this;
        }

        public Criteria andPapersidGreaterThanOrEqualTo(Integer value) {
            addCriterion("papersId >=", value, "papersid");
            return (Criteria) this;
        }

        public Criteria andPapersidLessThan(Integer value) {
            addCriterion("papersId <", value, "papersid");
            return (Criteria) this;
        }

        public Criteria andPapersidLessThanOrEqualTo(Integer value) {
            addCriterion("papersId <=", value, "papersid");
            return (Criteria) this;
        }

        public Criteria andPapersidIn(List<Integer> values) {
            addCriterion("papersId in", values, "papersid");
            return (Criteria) this;
        }

        public Criteria andPapersidNotIn(List<Integer> values) {
            addCriterion("papersId not in", values, "papersid");
            return (Criteria) this;
        }

        public Criteria andPapersidBetween(Integer value1, Integer value2) {
            addCriterion("papersId between", value1, value2, "papersid");
            return (Criteria) this;
        }

        public Criteria andPapersidNotBetween(Integer value1, Integer value2) {
            addCriterion("papersId not between", value1, value2, "papersid");
            return (Criteria) this;
        }

        public Criteria andClassnameIsNull() {
            addCriterion("className is null");
            return (Criteria) this;
        }

        public Criteria andClassnameIsNotNull() {
            addCriterion("className is not null");
            return (Criteria) this;
        }

        public Criteria andClassnameEqualTo(String value) {
            addCriterion("className =", value, "classname");
            return (Criteria) this;
        }

        public Criteria andClassnameNotEqualTo(String value) {
            addCriterion("className <>", value, "classname");
            return (Criteria) this;
        }

        public Criteria andClassnameGreaterThan(String value) {
            addCriterion("className >", value, "classname");
            return (Criteria) this;
        }

        public Criteria andClassnameGreaterThanOrEqualTo(String value) {
            addCriterion("className >=", value, "classname");
            return (Criteria) this;
        }

        public Criteria andClassnameLessThan(String value) {
            addCriterion("className <", value, "classname");
            return (Criteria) this;
        }

        public Criteria andClassnameLessThanOrEqualTo(String value) {
            addCriterion("className <=", value, "classname");
            return (Criteria) this;
        }

        public Criteria andClassnameLike(String value) {
            addCriterion("className like", value, "classname");
            return (Criteria) this;
        }

        public Criteria andClassnameNotLike(String value) {
            addCriterion("className not like", value, "classname");
            return (Criteria) this;
        }

        public Criteria andClassnameIn(List<String> values) {
            addCriterion("className in", values, "classname");
            return (Criteria) this;
        }

        public Criteria andClassnameNotIn(List<String> values) {
            addCriterion("className not in", values, "classname");
            return (Criteria) this;
        }

        public Criteria andClassnameBetween(String value1, String value2) {
            addCriterion("className between", value1, value2, "classname");
            return (Criteria) this;
        }

        public Criteria andClassnameNotBetween(String value1, String value2) {
            addCriterion("className not between", value1, value2, "classname");
            return (Criteria) this;
        }

        public Criteria andClasssortIsNull() {
            addCriterion("classSort is null");
            return (Criteria) this;
        }

        public Criteria andClasssortIsNotNull() {
            addCriterion("classSort is not null");
            return (Criteria) this;
        }

        public Criteria andClasssortEqualTo(Integer value) {
            addCriterion("classSort =", value, "classsort");
            return (Criteria) this;
        }

        public Criteria andClasssortNotEqualTo(Integer value) {
            addCriterion("classSort <>", value, "classsort");
            return (Criteria) this;
        }

        public Criteria andClasssortGreaterThan(Integer value) {
            addCriterion("classSort >", value, "classsort");
            return (Criteria) this;
        }

        public Criteria andClasssortGreaterThanOrEqualTo(Integer value) {
            addCriterion("classSort >=", value, "classsort");
            return (Criteria) this;
        }

        public Criteria andClasssortLessThan(Integer value) {
            addCriterion("classSort <", value, "classsort");
            return (Criteria) this;
        }

        public Criteria andClasssortLessThanOrEqualTo(Integer value) {
            addCriterion("classSort <=", value, "classsort");
            return (Criteria) this;
        }

        public Criteria andClasssortIn(List<Integer> values) {
            addCriterion("classSort in", values, "classsort");
            return (Criteria) this;
        }

        public Criteria andClasssortNotIn(List<Integer> values) {
            addCriterion("classSort not in", values, "classsort");
            return (Criteria) this;
        }

        public Criteria andClasssortBetween(Integer value1, Integer value2) {
            addCriterion("classSort between", value1, value2, "classsort");
            return (Criteria) this;
        }

        public Criteria andClasssortNotBetween(Integer value1, Integer value2) {
            addCriterion("classSort not between", value1, value2, "classsort");
            return (Criteria) this;
        }

        public Criteria andClassstatusIsNull() {
            addCriterion("classStatus is null");
            return (Criteria) this;
        }

        public Criteria andClassstatusIsNotNull() {
            addCriterion("classStatus is not null");
            return (Criteria) this;
        }

        public Criteria andClassstatusEqualTo(Integer value) {
            addCriterion("classStatus =", value, "classstatus");
            return (Criteria) this;
        }

        public Criteria andClassstatusNotEqualTo(Integer value) {
            addCriterion("classStatus <>", value, "classstatus");
            return (Criteria) this;
        }

        public Criteria andClassstatusGreaterThan(Integer value) {
            addCriterion("classStatus >", value, "classstatus");
            return (Criteria) this;
        }

        public Criteria andClassstatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("classStatus >=", value, "classstatus");
            return (Criteria) this;
        }

        public Criteria andClassstatusLessThan(Integer value) {
            addCriterion("classStatus <", value, "classstatus");
            return (Criteria) this;
        }

        public Criteria andClassstatusLessThanOrEqualTo(Integer value) {
            addCriterion("classStatus <=", value, "classstatus");
            return (Criteria) this;
        }

        public Criteria andClassstatusIn(List<Integer> values) {
            addCriterion("classStatus in", values, "classstatus");
            return (Criteria) this;
        }

        public Criteria andClassstatusNotIn(List<Integer> values) {
            addCriterion("classStatus not in", values, "classstatus");
            return (Criteria) this;
        }

        public Criteria andClassstatusBetween(Integer value1, Integer value2) {
            addCriterion("classStatus between", value1, value2, "classstatus");
            return (Criteria) this;
        }

        public Criteria andClassstatusNotBetween(Integer value1, Integer value2) {
            addCriterion("classStatus not between", value1, value2, "classstatus");
            return (Criteria) this;
        }

        public Criteria andClasscountIsNull() {
            addCriterion("classCount is null");
            return (Criteria) this;
        }

        public Criteria andClasscountIsNotNull() {
            addCriterion("classCount is not null");
            return (Criteria) this;
        }

        public Criteria andClasscountEqualTo(Integer value) {
            addCriterion("classCount =", value, "classcount");
            return (Criteria) this;
        }

        public Criteria andClasscountNotEqualTo(Integer value) {
            addCriterion("classCount <>", value, "classcount");
            return (Criteria) this;
        }

        public Criteria andClasscountGreaterThan(Integer value) {
            addCriterion("classCount >", value, "classcount");
            return (Criteria) this;
        }

        public Criteria andClasscountGreaterThanOrEqualTo(Integer value) {
            addCriterion("classCount >=", value, "classcount");
            return (Criteria) this;
        }

        public Criteria andClasscountLessThan(Integer value) {
            addCriterion("classCount <", value, "classcount");
            return (Criteria) this;
        }

        public Criteria andClasscountLessThanOrEqualTo(Integer value) {
            addCriterion("classCount <=", value, "classcount");
            return (Criteria) this;
        }

        public Criteria andClasscountIn(List<Integer> values) {
            addCriterion("classCount in", values, "classcount");
            return (Criteria) this;
        }

        public Criteria andClasscountNotIn(List<Integer> values) {
            addCriterion("classCount not in", values, "classcount");
            return (Criteria) this;
        }

        public Criteria andClasscountBetween(Integer value1, Integer value2) {
            addCriterion("classCount between", value1, value2, "classcount");
            return (Criteria) this;
        }

        public Criteria andClasscountNotBetween(Integer value1, Integer value2) {
            addCriterion("classCount not between", value1, value2, "classcount");
            return (Criteria) this;
        }

        public Criteria andClasspidIsNull() {
            addCriterion("classPid is null");
            return (Criteria) this;
        }

        public Criteria andClasspidIsNotNull() {
            addCriterion("classPid is not null");
            return (Criteria) this;
        }

        public Criteria andClasspidEqualTo(Integer value) {
            addCriterion("classPid =", value, "classpid");
            return (Criteria) this;
        }

        public Criteria andClasspidNotEqualTo(Integer value) {
            addCriterion("classPid <>", value, "classpid");
            return (Criteria) this;
        }

        public Criteria andClasspidGreaterThan(Integer value) {
            addCriterion("classPid >", value, "classpid");
            return (Criteria) this;
        }

        public Criteria andClasspidGreaterThanOrEqualTo(Integer value) {
            addCriterion("classPid >=", value, "classpid");
            return (Criteria) this;
        }

        public Criteria andClasspidLessThan(Integer value) {
            addCriterion("classPid <", value, "classpid");
            return (Criteria) this;
        }

        public Criteria andClasspidLessThanOrEqualTo(Integer value) {
            addCriterion("classPid <=", value, "classpid");
            return (Criteria) this;
        }

        public Criteria andClasspidIn(List<Integer> values) {
            addCriterion("classPid in", values, "classpid");
            return (Criteria) this;
        }

        public Criteria andClasspidNotIn(List<Integer> values) {
            addCriterion("classPid not in", values, "classpid");
            return (Criteria) this;
        }

        public Criteria andClasspidBetween(Integer value1, Integer value2) {
            addCriterion("classPid between", value1, value2, "classpid");
            return (Criteria) this;
        }

        public Criteria andClasspidNotBetween(Integer value1, Integer value2) {
            addCriterion("classPid not between", value1, value2, "classpid");
            return (Criteria) this;
        }

        public Criteria andLeafIsNull() {
            addCriterion("leaf is null");
            return (Criteria) this;
        }

        public Criteria andLeafIsNotNull() {
            addCriterion("leaf is not null");
            return (Criteria) this;
        }

        public Criteria andLeafEqualTo(Integer value) {
            addCriterion("leaf =", value, "leaf");
            return (Criteria) this;
        }

        public Criteria andLeafNotEqualTo(Integer value) {
            addCriterion("leaf <>", value, "leaf");
            return (Criteria) this;
        }

        public Criteria andLeafGreaterThan(Integer value) {
            addCriterion("leaf >", value, "leaf");
            return (Criteria) this;
        }

        public Criteria andLeafGreaterThanOrEqualTo(Integer value) {
            addCriterion("leaf >=", value, "leaf");
            return (Criteria) this;
        }

        public Criteria andLeafLessThan(Integer value) {
            addCriterion("leaf <", value, "leaf");
            return (Criteria) this;
        }

        public Criteria andLeafLessThanOrEqualTo(Integer value) {
            addCriterion("leaf <=", value, "leaf");
            return (Criteria) this;
        }

        public Criteria andLeafIn(List<Integer> values) {
            addCriterion("leaf in", values, "leaf");
            return (Criteria) this;
        }

        public Criteria andLeafNotIn(List<Integer> values) {
            addCriterion("leaf not in", values, "leaf");
            return (Criteria) this;
        }

        public Criteria andLeafBetween(Integer value1, Integer value2) {
            addCriterion("leaf between", value1, value2, "leaf");
            return (Criteria) this;
        }

        public Criteria andLeafNotBetween(Integer value1, Integer value2) {
            addCriterion("leaf not between", value1, value2, "leaf");
            return (Criteria) this;
        }

        public Criteria andClassnameLikeInsensitive(String value) {
            addCriterion("upper(className) like", value.toUpperCase(), "classname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated do_not_delete_during_merge Tue Sep 27 10:01:10 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mb_contentclasstemplates
     *
     * @mbggenerated Tue Sep 27 10:01:10 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}