package com.ezhuanbing.api.dao.mybatis.model;

import javax.persistence.Id;
import javax.persistence.Table;

@Table(name = "mb_contentclasstemplates")
public class ContentClassTemplates {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * mb_contentclasstemplates.id
   *
   * @mbggenerated Tue Sep 27 10:01:10 CST 2016
   */
  @Id
  private Integer id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * mb_contentclasstemplates.papersId
   *
   * @mbggenerated Tue Sep 27 10:01:10 CST 2016
   */
  private Integer papersid;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * mb_contentclasstemplates.className
   *
   * @mbggenerated Tue Sep 27 10:01:10 CST 2016
   */
  private String classname;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * mb_contentclasstemplates.classSort
   *
   * @mbggenerated Tue Sep 27 10:01:10 CST 2016
   */
  private Integer classsort;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * mb_contentclasstemplates.classStatus
   *
   * @mbggenerated Tue Sep 27 10:01:10 CST 2016
   */
  private Integer classstatus;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * mb_contentclasstemplates.classCount
   *
   * @mbggenerated Tue Sep 27 10:01:10 CST 2016
   */
  private Integer classcount;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * mb_contentclasstemplates.classPid
   *
   * @mbggenerated Tue Sep 27 10:01:10 CST 2016
   */
  private Integer classpid;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * mb_contentclasstemplates.leaf
   *
   * @mbggenerated Tue Sep 27 10:01:10 CST 2016
   */
  private Integer leaf;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column mb_contentclasstemplates.id
   *
   * @return the value of mb_contentclasstemplates.id
   *
   * @mbggenerated Tue Sep 27 10:01:10 CST 2016
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column mb_contentclasstemplates.id
   *
   * @param id the value for mb_contentclasstemplates.id
   *
   * @mbggenerated Tue Sep 27 10:01:10 CST 2016
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column mb_contentclasstemplates.papersId
   *
   * @return the value of mb_contentclasstemplates.papersId
   *
   * @mbggenerated Tue Sep 27 10:01:10 CST 2016
   */
  public Integer getPapersid() {
    return papersid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column mb_contentclasstemplates.papersId
   *
   * @param papersid the value for mb_contentclasstemplates.papersId
   *
   * @mbggenerated Tue Sep 27 10:01:10 CST 2016
   */
  public void setPapersid(Integer papersid) {
    this.papersid = papersid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column mb_contentclasstemplates.className
   *
   * @return the value of mb_contentclasstemplates.className
   *
   * @mbggenerated Tue Sep 27 10:01:10 CST 2016
   */
  public String getClassname() {
    return classname;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column mb_contentclasstemplates.className
   *
   * @param classname the value for mb_contentclasstemplates.className
   *
   * @mbggenerated Tue Sep 27 10:01:10 CST 2016
   */
  public void setClassname(String classname) {
    this.classname = classname == null ? null : classname.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column mb_contentclasstemplates.classSort
   *
   * @return the value of mb_contentclasstemplates.classSort
   *
   * @mbggenerated Tue Sep 27 10:01:10 CST 2016
   */
  public Integer getClasssort() {
    return classsort;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column mb_contentclasstemplates.classSort
   *
   * @param classsort the value for mb_contentclasstemplates.classSort
   *
   * @mbggenerated Tue Sep 27 10:01:10 CST 2016
   */
  public void setClasssort(Integer classsort) {
    this.classsort = classsort;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column mb_contentclasstemplates.classStatus
   *
   * @return the value of mb_contentclasstemplates.classStatus
   *
   * @mbggenerated Tue Sep 27 10:01:10 CST 2016
   */
  public Integer getClassstatus() {
    return classstatus;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column mb_contentclasstemplates.classStatus
   *
   * @param classstatus the value for mb_contentclasstemplates.classStatus
   *
   * @mbggenerated Tue Sep 27 10:01:10 CST 2016
   */
  public void setClassstatus(Integer classstatus) {
    this.classstatus = classstatus;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column mb_contentclasstemplates.classCount
   *
   * @return the value of mb_contentclasstemplates.classCount
   *
   * @mbggenerated Tue Sep 27 10:01:10 CST 2016
   */
  public Integer getClasscount() {
    return classcount;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column mb_contentclasstemplates.classCount
   *
   * @param classcount the value for mb_contentclasstemplates.classCount
   *
   * @mbggenerated Tue Sep 27 10:01:10 CST 2016
   */
  public void setClasscount(Integer classcount) {
    this.classcount = classcount;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column mb_contentclasstemplates.classPid
   *
   * @return the value of mb_contentclasstemplates.classPid
   *
   * @mbggenerated Tue Sep 27 10:01:10 CST 2016
   */
  public Integer getClasspid() {
    return classpid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column mb_contentclasstemplates.classPid
   *
   * @param classpid the value for mb_contentclasstemplates.classPid
   *
   * @mbggenerated Tue Sep 27 10:01:10 CST 2016
   */
  public void setClasspid(Integer classpid) {
    this.classpid = classpid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column mb_contentclasstemplates.leaf
   *
   * @return the value of mb_contentclasstemplates.leaf
   *
   * @mbggenerated Tue Sep 27 10:01:10 CST 2016
   */
  public Integer getLeaf() {
    return leaf;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column mb_contentclasstemplates.leaf
   *
   * @param leaf the value for mb_contentclasstemplates.leaf
   *
   * @mbggenerated Tue Sep 27 10:01:10 CST 2016
   */
  public void setLeaf(Integer leaf) {
    this.leaf = leaf;
  }
}
