package com.ezhuanbing.api.dao.mybatis.model;

public class EducationFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_educationfile.id
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_educationfile.title
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_educationfile.thumbnailUrl
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    private String thumbnailurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_educationfile.profile
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    private String profile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_educationfile.fileUrl
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    private String fileurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_educationfile.status
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_educationfile.id
     *
     * @return the value of mb_educationfile.id
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_educationfile.id
     *
     * @param id the value for mb_educationfile.id
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_educationfile.title
     *
     * @return the value of mb_educationfile.title
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_educationfile.title
     *
     * @param title the value for mb_educationfile.title
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_educationfile.thumbnailUrl
     *
     * @return the value of mb_educationfile.thumbnailUrl
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    public String getThumbnailurl() {
        return thumbnailurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_educationfile.thumbnailUrl
     *
     * @param thumbnailurl the value for mb_educationfile.thumbnailUrl
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    public void setThumbnailurl(String thumbnailurl) {
        this.thumbnailurl = thumbnailurl == null ? null : thumbnailurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_educationfile.profile
     *
     * @return the value of mb_educationfile.profile
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    public String getProfile() {
        return profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_educationfile.profile
     *
     * @param profile the value for mb_educationfile.profile
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    public void setProfile(String profile) {
        this.profile = profile == null ? null : profile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_educationfile.fileUrl
     *
     * @return the value of mb_educationfile.fileUrl
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    public String getFileurl() {
        return fileurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_educationfile.fileUrl
     *
     * @param fileurl the value for mb_educationfile.fileUrl
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    public void setFileurl(String fileurl) {
        this.fileurl = fileurl == null ? null : fileurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_educationfile.status
     *
     * @return the value of mb_educationfile.status
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_educationfile.status
     *
     * @param status the value for mb_educationfile.status
     *
     * @mbggenerated Sat Sep 10 11:27:18 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}