package com.ezhuanbing.api.dao.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class OptionTemplatesCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public OptionTemplatesCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andQuestionstemplatesidIsNull() {
            addCriterion("questionsTemplatesId is null");
            return (Criteria) this;
        }

        public Criteria andQuestionstemplatesidIsNotNull() {
            addCriterion("questionsTemplatesId is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionstemplatesidEqualTo(Integer value) {
            addCriterion("questionsTemplatesId =", value, "questionstemplatesid");
            return (Criteria) this;
        }

        public Criteria andQuestionstemplatesidNotEqualTo(Integer value) {
            addCriterion("questionsTemplatesId <>", value, "questionstemplatesid");
            return (Criteria) this;
        }

        public Criteria andQuestionstemplatesidGreaterThan(Integer value) {
            addCriterion("questionsTemplatesId >", value, "questionstemplatesid");
            return (Criteria) this;
        }

        public Criteria andQuestionstemplatesidGreaterThanOrEqualTo(Integer value) {
            addCriterion("questionsTemplatesId >=", value, "questionstemplatesid");
            return (Criteria) this;
        }

        public Criteria andQuestionstemplatesidLessThan(Integer value) {
            addCriterion("questionsTemplatesId <", value, "questionstemplatesid");
            return (Criteria) this;
        }

        public Criteria andQuestionstemplatesidLessThanOrEqualTo(Integer value) {
            addCriterion("questionsTemplatesId <=", value, "questionstemplatesid");
            return (Criteria) this;
        }

        public Criteria andQuestionstemplatesidIn(List<Integer> values) {
            addCriterion("questionsTemplatesId in", values, "questionstemplatesid");
            return (Criteria) this;
        }

        public Criteria andQuestionstemplatesidNotIn(List<Integer> values) {
            addCriterion("questionsTemplatesId not in", values, "questionstemplatesid");
            return (Criteria) this;
        }

        public Criteria andQuestionstemplatesidBetween(Integer value1, Integer value2) {
            addCriterion("questionsTemplatesId between", value1, value2, "questionstemplatesid");
            return (Criteria) this;
        }

        public Criteria andQuestionstemplatesidNotBetween(Integer value1, Integer value2) {
            addCriterion("questionsTemplatesId not between", value1, value2, "questionstemplatesid");
            return (Criteria) this;
        }

        public Criteria andOptionnumberIsNull() {
            addCriterion("optionNumber is null");
            return (Criteria) this;
        }

        public Criteria andOptionnumberIsNotNull() {
            addCriterion("optionNumber is not null");
            return (Criteria) this;
        }

        public Criteria andOptionnumberEqualTo(String value) {
            addCriterion("optionNumber =", value, "optionnumber");
            return (Criteria) this;
        }

        public Criteria andOptionnumberNotEqualTo(String value) {
            addCriterion("optionNumber <>", value, "optionnumber");
            return (Criteria) this;
        }

        public Criteria andOptionnumberGreaterThan(String value) {
            addCriterion("optionNumber >", value, "optionnumber");
            return (Criteria) this;
        }

        public Criteria andOptionnumberGreaterThanOrEqualTo(String value) {
            addCriterion("optionNumber >=", value, "optionnumber");
            return (Criteria) this;
        }

        public Criteria andOptionnumberLessThan(String value) {
            addCriterion("optionNumber <", value, "optionnumber");
            return (Criteria) this;
        }

        public Criteria andOptionnumberLessThanOrEqualTo(String value) {
            addCriterion("optionNumber <=", value, "optionnumber");
            return (Criteria) this;
        }

        public Criteria andOptionnumberLike(String value) {
            addCriterion("optionNumber like", value, "optionnumber");
            return (Criteria) this;
        }

        public Criteria andOptionnumberNotLike(String value) {
            addCriterion("optionNumber not like", value, "optionnumber");
            return (Criteria) this;
        }

        public Criteria andOptionnumberIn(List<String> values) {
            addCriterion("optionNumber in", values, "optionnumber");
            return (Criteria) this;
        }

        public Criteria andOptionnumberNotIn(List<String> values) {
            addCriterion("optionNumber not in", values, "optionnumber");
            return (Criteria) this;
        }

        public Criteria andOptionnumberBetween(String value1, String value2) {
            addCriterion("optionNumber between", value1, value2, "optionnumber");
            return (Criteria) this;
        }

        public Criteria andOptionnumberNotBetween(String value1, String value2) {
            addCriterion("optionNumber not between", value1, value2, "optionnumber");
            return (Criteria) this;
        }

        public Criteria andOptiontypeIsNull() {
            addCriterion("optionType is null");
            return (Criteria) this;
        }

        public Criteria andOptiontypeIsNotNull() {
            addCriterion("optionType is not null");
            return (Criteria) this;
        }

        public Criteria andOptiontypeEqualTo(Integer value) {
            addCriterion("optionType =", value, "optiontype");
            return (Criteria) this;
        }

        public Criteria andOptiontypeNotEqualTo(Integer value) {
            addCriterion("optionType <>", value, "optiontype");
            return (Criteria) this;
        }

        public Criteria andOptiontypeGreaterThan(Integer value) {
            addCriterion("optionType >", value, "optiontype");
            return (Criteria) this;
        }

        public Criteria andOptiontypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("optionType >=", value, "optiontype");
            return (Criteria) this;
        }

        public Criteria andOptiontypeLessThan(Integer value) {
            addCriterion("optionType <", value, "optiontype");
            return (Criteria) this;
        }

        public Criteria andOptiontypeLessThanOrEqualTo(Integer value) {
            addCriterion("optionType <=", value, "optiontype");
            return (Criteria) this;
        }

        public Criteria andOptiontypeIn(List<Integer> values) {
            addCriterion("optionType in", values, "optiontype");
            return (Criteria) this;
        }

        public Criteria andOptiontypeNotIn(List<Integer> values) {
            addCriterion("optionType not in", values, "optiontype");
            return (Criteria) this;
        }

        public Criteria andOptiontypeBetween(Integer value1, Integer value2) {
            addCriterion("optionType between", value1, value2, "optiontype");
            return (Criteria) this;
        }

        public Criteria andOptiontypeNotBetween(Integer value1, Integer value2) {
            addCriterion("optionType not between", value1, value2, "optiontype");
            return (Criteria) this;
        }

        public Criteria andOptionpictureIsNull() {
            addCriterion("optionPicture is null");
            return (Criteria) this;
        }

        public Criteria andOptionpictureIsNotNull() {
            addCriterion("optionPicture is not null");
            return (Criteria) this;
        }

        public Criteria andOptionpictureEqualTo(String value) {
            addCriterion("optionPicture =", value, "optionpicture");
            return (Criteria) this;
        }

        public Criteria andOptionpictureNotEqualTo(String value) {
            addCriterion("optionPicture <>", value, "optionpicture");
            return (Criteria) this;
        }

        public Criteria andOptionpictureGreaterThan(String value) {
            addCriterion("optionPicture >", value, "optionpicture");
            return (Criteria) this;
        }

        public Criteria andOptionpictureGreaterThanOrEqualTo(String value) {
            addCriterion("optionPicture >=", value, "optionpicture");
            return (Criteria) this;
        }

        public Criteria andOptionpictureLessThan(String value) {
            addCriterion("optionPicture <", value, "optionpicture");
            return (Criteria) this;
        }

        public Criteria andOptionpictureLessThanOrEqualTo(String value) {
            addCriterion("optionPicture <=", value, "optionpicture");
            return (Criteria) this;
        }

        public Criteria andOptionpictureLike(String value) {
            addCriterion("optionPicture like", value, "optionpicture");
            return (Criteria) this;
        }

        public Criteria andOptionpictureNotLike(String value) {
            addCriterion("optionPicture not like", value, "optionpicture");
            return (Criteria) this;
        }

        public Criteria andOptionpictureIn(List<String> values) {
            addCriterion("optionPicture in", values, "optionpicture");
            return (Criteria) this;
        }

        public Criteria andOptionpictureNotIn(List<String> values) {
            addCriterion("optionPicture not in", values, "optionpicture");
            return (Criteria) this;
        }

        public Criteria andOptionpictureBetween(String value1, String value2) {
            addCriterion("optionPicture between", value1, value2, "optionpicture");
            return (Criteria) this;
        }

        public Criteria andOptionpictureNotBetween(String value1, String value2) {
            addCriterion("optionPicture not between", value1, value2, "optionpicture");
            return (Criteria) this;
        }

        public Criteria andOptionresultcountIsNull() {
            addCriterion("optionResultCount is null");
            return (Criteria) this;
        }

        public Criteria andOptionresultcountIsNotNull() {
            addCriterion("optionResultCount is not null");
            return (Criteria) this;
        }

        public Criteria andOptionresultcountEqualTo(Integer value) {
            addCriterion("optionResultCount =", value, "optionresultcount");
            return (Criteria) this;
        }

        public Criteria andOptionresultcountNotEqualTo(Integer value) {
            addCriterion("optionResultCount <>", value, "optionresultcount");
            return (Criteria) this;
        }

        public Criteria andOptionresultcountGreaterThan(Integer value) {
            addCriterion("optionResultCount >", value, "optionresultcount");
            return (Criteria) this;
        }

        public Criteria andOptionresultcountGreaterThanOrEqualTo(Integer value) {
            addCriterion("optionResultCount >=", value, "optionresultcount");
            return (Criteria) this;
        }

        public Criteria andOptionresultcountLessThan(Integer value) {
            addCriterion("optionResultCount <", value, "optionresultcount");
            return (Criteria) this;
        }

        public Criteria andOptionresultcountLessThanOrEqualTo(Integer value) {
            addCriterion("optionResultCount <=", value, "optionresultcount");
            return (Criteria) this;
        }

        public Criteria andOptionresultcountIn(List<Integer> values) {
            addCriterion("optionResultCount in", values, "optionresultcount");
            return (Criteria) this;
        }

        public Criteria andOptionresultcountNotIn(List<Integer> values) {
            addCriterion("optionResultCount not in", values, "optionresultcount");
            return (Criteria) this;
        }

        public Criteria andOptionresultcountBetween(Integer value1, Integer value2) {
            addCriterion("optionResultCount between", value1, value2, "optionresultcount");
            return (Criteria) this;
        }

        public Criteria andOptionresultcountNotBetween(Integer value1, Integer value2) {
            addCriterion("optionResultCount not between", value1, value2, "optionresultcount");
            return (Criteria) this;
        }

        public Criteria andOptionnumberLikeInsensitive(String value) {
            addCriterion("upper(optionNumber) like", value.toUpperCase(), "optionnumber");
            return (Criteria) this;
        }

        public Criteria andOptionpictureLikeInsensitive(String value) {
            addCriterion("upper(optionPicture) like", value.toUpperCase(), "optionpicture");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated do_not_delete_during_merge Tue Sep 06 17:31:57 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mb_optiontemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}