package com.ezhuanbing.api.dao.mybatis.model;

public class OptionTemplates {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_optiontemplates.id
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_optiontemplates.questionsTemplatesId
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    private Integer questionstemplatesid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_optiontemplates.optionNumber
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    private String optionnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_optiontemplates.optionType
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    private Integer optiontype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_optiontemplates.optionPicture
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    private String optionpicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_optiontemplates.optionResultCount
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    private Integer optionresultcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_optiontemplates.optionContent
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    private String optioncontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_optiontemplates.id
     *
     * @return the value of mb_optiontemplates.id
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_optiontemplates.id
     *
     * @param id the value for mb_optiontemplates.id
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_optiontemplates.questionsTemplatesId
     *
     * @return the value of mb_optiontemplates.questionsTemplatesId
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public Integer getQuestionstemplatesid() {
        return questionstemplatesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_optiontemplates.questionsTemplatesId
     *
     * @param questionstemplatesid the value for mb_optiontemplates.questionsTemplatesId
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void setQuestionstemplatesid(Integer questionstemplatesid) {
        this.questionstemplatesid = questionstemplatesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_optiontemplates.optionNumber
     *
     * @return the value of mb_optiontemplates.optionNumber
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public String getOptionnumber() {
        return optionnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_optiontemplates.optionNumber
     *
     * @param optionnumber the value for mb_optiontemplates.optionNumber
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void setOptionnumber(String optionnumber) {
        this.optionnumber = optionnumber == null ? null : optionnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_optiontemplates.optionType
     *
     * @return the value of mb_optiontemplates.optionType
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public Integer getOptiontype() {
        return optiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_optiontemplates.optionType
     *
     * @param optiontype the value for mb_optiontemplates.optionType
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void setOptiontype(Integer optiontype) {
        this.optiontype = optiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_optiontemplates.optionPicture
     *
     * @return the value of mb_optiontemplates.optionPicture
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public String getOptionpicture() {
        return optionpicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_optiontemplates.optionPicture
     *
     * @param optionpicture the value for mb_optiontemplates.optionPicture
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void setOptionpicture(String optionpicture) {
        this.optionpicture = optionpicture == null ? null : optionpicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_optiontemplates.optionResultCount
     *
     * @return the value of mb_optiontemplates.optionResultCount
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public Integer getOptionresultcount() {
        return optionresultcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_optiontemplates.optionResultCount
     *
     * @param optionresultcount the value for mb_optiontemplates.optionResultCount
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void setOptionresultcount(Integer optionresultcount) {
        this.optionresultcount = optionresultcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_optiontemplates.optionContent
     *
     * @return the value of mb_optiontemplates.optionContent
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public String getOptioncontent() {
        return optioncontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_optiontemplates.optionContent
     *
     * @param optioncontent the value for mb_optiontemplates.optionContent
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void setOptioncontent(String optioncontent) {
        this.optioncontent = optioncontent == null ? null : optioncontent.trim();
    }
}