package com.ezhuanbing.api.dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PapersTemplatesCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public PapersTemplatesCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("userName is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("userName is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("userName =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("userName <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("userName >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("userName >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("userName <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("userName <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("userName like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("userName not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("userName in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("userName not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("userName between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("userName not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameidIsNull() {
            addCriterion("userNameId is null");
            return (Criteria) this;
        }

        public Criteria andUsernameidIsNotNull() {
            addCriterion("userNameId is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameidEqualTo(Integer value) {
            addCriterion("userNameId =", value, "usernameid");
            return (Criteria) this;
        }

        public Criteria andUsernameidNotEqualTo(Integer value) {
            addCriterion("userNameId <>", value, "usernameid");
            return (Criteria) this;
        }

        public Criteria andUsernameidGreaterThan(Integer value) {
            addCriterion("userNameId >", value, "usernameid");
            return (Criteria) this;
        }

        public Criteria andUsernameidGreaterThanOrEqualTo(Integer value) {
            addCriterion("userNameId >=", value, "usernameid");
            return (Criteria) this;
        }

        public Criteria andUsernameidLessThan(Integer value) {
            addCriterion("userNameId <", value, "usernameid");
            return (Criteria) this;
        }

        public Criteria andUsernameidLessThanOrEqualTo(Integer value) {
            addCriterion("userNameId <=", value, "usernameid");
            return (Criteria) this;
        }

        public Criteria andUsernameidIn(List<Integer> values) {
            addCriterion("userNameId in", values, "usernameid");
            return (Criteria) this;
        }

        public Criteria andUsernameidNotIn(List<Integer> values) {
            addCriterion("userNameId not in", values, "usernameid");
            return (Criteria) this;
        }

        public Criteria andUsernameidBetween(Integer value1, Integer value2) {
            addCriterion("userNameId between", value1, value2, "usernameid");
            return (Criteria) this;
        }

        public Criteria andUsernameidNotBetween(Integer value1, Integer value2) {
            addCriterion("userNameId not between", value1, value2, "usernameid");
            return (Criteria) this;
        }

        public Criteria andPapertileIsNull() {
            addCriterion("paperTile is null");
            return (Criteria) this;
        }

        public Criteria andPapertileIsNotNull() {
            addCriterion("paperTile is not null");
            return (Criteria) this;
        }

        public Criteria andPapertileEqualTo(String value) {
            addCriterion("paperTile =", value, "papertile");
            return (Criteria) this;
        }

        public Criteria andPapertileNotEqualTo(String value) {
            addCriterion("paperTile <>", value, "papertile");
            return (Criteria) this;
        }

        public Criteria andPapertileGreaterThan(String value) {
            addCriterion("paperTile >", value, "papertile");
            return (Criteria) this;
        }

        public Criteria andPapertileGreaterThanOrEqualTo(String value) {
            addCriterion("paperTile >=", value, "papertile");
            return (Criteria) this;
        }

        public Criteria andPapertileLessThan(String value) {
            addCriterion("paperTile <", value, "papertile");
            return (Criteria) this;
        }

        public Criteria andPapertileLessThanOrEqualTo(String value) {
            addCriterion("paperTile <=", value, "papertile");
            return (Criteria) this;
        }

        public Criteria andPapertileLike(String value) {
            addCriterion("paperTile like", value, "papertile");
            return (Criteria) this;
        }

        public Criteria andPapertileNotLike(String value) {
            addCriterion("paperTile not like", value, "papertile");
            return (Criteria) this;
        }

        public Criteria andPapertileIn(List<String> values) {
            addCriterion("paperTile in", values, "papertile");
            return (Criteria) this;
        }

        public Criteria andPapertileNotIn(List<String> values) {
            addCriterion("paperTile not in", values, "papertile");
            return (Criteria) this;
        }

        public Criteria andPapertileBetween(String value1, String value2) {
            addCriterion("paperTile between", value1, value2, "papertile");
            return (Criteria) this;
        }

        public Criteria andPapertileNotBetween(String value1, String value2) {
            addCriterion("paperTile not between", value1, value2, "papertile");
            return (Criteria) this;
        }

        public Criteria andPapersummaryIsNull() {
            addCriterion("paperSummary is null");
            return (Criteria) this;
        }

        public Criteria andPapersummaryIsNotNull() {
            addCriterion("paperSummary is not null");
            return (Criteria) this;
        }

        public Criteria andPapersummaryEqualTo(String value) {
            addCriterion("paperSummary =", value, "papersummary");
            return (Criteria) this;
        }

        public Criteria andPapersummaryNotEqualTo(String value) {
            addCriterion("paperSummary <>", value, "papersummary");
            return (Criteria) this;
        }

        public Criteria andPapersummaryGreaterThan(String value) {
            addCriterion("paperSummary >", value, "papersummary");
            return (Criteria) this;
        }

        public Criteria andPapersummaryGreaterThanOrEqualTo(String value) {
            addCriterion("paperSummary >=", value, "papersummary");
            return (Criteria) this;
        }

        public Criteria andPapersummaryLessThan(String value) {
            addCriterion("paperSummary <", value, "papersummary");
            return (Criteria) this;
        }

        public Criteria andPapersummaryLessThanOrEqualTo(String value) {
            addCriterion("paperSummary <=", value, "papersummary");
            return (Criteria) this;
        }

        public Criteria andPapersummaryLike(String value) {
            addCriterion("paperSummary like", value, "papersummary");
            return (Criteria) this;
        }

        public Criteria andPapersummaryNotLike(String value) {
            addCriterion("paperSummary not like", value, "papersummary");
            return (Criteria) this;
        }

        public Criteria andPapersummaryIn(List<String> values) {
            addCriterion("paperSummary in", values, "papersummary");
            return (Criteria) this;
        }

        public Criteria andPapersummaryNotIn(List<String> values) {
            addCriterion("paperSummary not in", values, "papersummary");
            return (Criteria) this;
        }

        public Criteria andPapersummaryBetween(String value1, String value2) {
            addCriterion("paperSummary between", value1, value2, "papersummary");
            return (Criteria) this;
        }

        public Criteria andPapersummaryNotBetween(String value1, String value2) {
            addCriterion("paperSummary not between", value1, value2, "papersummary");
            return (Criteria) this;
        }

        public Criteria andPaperstartdateIsNull() {
            addCriterion("paperStartDate is null");
            return (Criteria) this;
        }

        public Criteria andPaperstartdateIsNotNull() {
            addCriterion("paperStartDate is not null");
            return (Criteria) this;
        }

        public Criteria andPaperstartdateEqualTo(Date value) {
            addCriterion("paperStartDate =", value, "paperstartdate");
            return (Criteria) this;
        }

        public Criteria andPaperstartdateNotEqualTo(Date value) {
            addCriterion("paperStartDate <>", value, "paperstartdate");
            return (Criteria) this;
        }

        public Criteria andPaperstartdateGreaterThan(Date value) {
            addCriterion("paperStartDate >", value, "paperstartdate");
            return (Criteria) this;
        }

        public Criteria andPaperstartdateGreaterThanOrEqualTo(Date value) {
            addCriterion("paperStartDate >=", value, "paperstartdate");
            return (Criteria) this;
        }

        public Criteria andPaperstartdateLessThan(Date value) {
            addCriterion("paperStartDate <", value, "paperstartdate");
            return (Criteria) this;
        }

        public Criteria andPaperstartdateLessThanOrEqualTo(Date value) {
            addCriterion("paperStartDate <=", value, "paperstartdate");
            return (Criteria) this;
        }

        public Criteria andPaperstartdateIn(List<Date> values) {
            addCriterion("paperStartDate in", values, "paperstartdate");
            return (Criteria) this;
        }

        public Criteria andPaperstartdateNotIn(List<Date> values) {
            addCriterion("paperStartDate not in", values, "paperstartdate");
            return (Criteria) this;
        }

        public Criteria andPaperstartdateBetween(Date value1, Date value2) {
            addCriterion("paperStartDate between", value1, value2, "paperstartdate");
            return (Criteria) this;
        }

        public Criteria andPaperstartdateNotBetween(Date value1, Date value2) {
            addCriterion("paperStartDate not between", value1, value2, "paperstartdate");
            return (Criteria) this;
        }

        public Criteria andPaperbgIsNull() {
            addCriterion("paperBg is null");
            return (Criteria) this;
        }

        public Criteria andPaperbgIsNotNull() {
            addCriterion("paperBg is not null");
            return (Criteria) this;
        }

        public Criteria andPaperbgEqualTo(String value) {
            addCriterion("paperBg =", value, "paperbg");
            return (Criteria) this;
        }

        public Criteria andPaperbgNotEqualTo(String value) {
            addCriterion("paperBg <>", value, "paperbg");
            return (Criteria) this;
        }

        public Criteria andPaperbgGreaterThan(String value) {
            addCriterion("paperBg >", value, "paperbg");
            return (Criteria) this;
        }

        public Criteria andPaperbgGreaterThanOrEqualTo(String value) {
            addCriterion("paperBg >=", value, "paperbg");
            return (Criteria) this;
        }

        public Criteria andPaperbgLessThan(String value) {
            addCriterion("paperBg <", value, "paperbg");
            return (Criteria) this;
        }

        public Criteria andPaperbgLessThanOrEqualTo(String value) {
            addCriterion("paperBg <=", value, "paperbg");
            return (Criteria) this;
        }

        public Criteria andPaperbgLike(String value) {
            addCriterion("paperBg like", value, "paperbg");
            return (Criteria) this;
        }

        public Criteria andPaperbgNotLike(String value) {
            addCriterion("paperBg not like", value, "paperbg");
            return (Criteria) this;
        }

        public Criteria andPaperbgIn(List<String> values) {
            addCriterion("paperBg in", values, "paperbg");
            return (Criteria) this;
        }

        public Criteria andPaperbgNotIn(List<String> values) {
            addCriterion("paperBg not in", values, "paperbg");
            return (Criteria) this;
        }

        public Criteria andPaperbgBetween(String value1, String value2) {
            addCriterion("paperBg between", value1, value2, "paperbg");
            return (Criteria) this;
        }

        public Criteria andPaperbgNotBetween(String value1, String value2) {
            addCriterion("paperBg not between", value1, value2, "paperbg");
            return (Criteria) this;
        }

        public Criteria andPapertypeIsNull() {
            addCriterion("paperType is null");
            return (Criteria) this;
        }

        public Criteria andPapertypeIsNotNull() {
            addCriterion("paperType is not null");
            return (Criteria) this;
        }

        public Criteria andPapertypeEqualTo(Integer value) {
            addCriterion("paperType =", value, "papertype");
            return (Criteria) this;
        }

        public Criteria andPapertypeNotEqualTo(Integer value) {
            addCriterion("paperType <>", value, "papertype");
            return (Criteria) this;
        }

        public Criteria andPapertypeGreaterThan(Integer value) {
            addCriterion("paperType >", value, "papertype");
            return (Criteria) this;
        }

        public Criteria andPapertypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("paperType >=", value, "papertype");
            return (Criteria) this;
        }

        public Criteria andPapertypeLessThan(Integer value) {
            addCriterion("paperType <", value, "papertype");
            return (Criteria) this;
        }

        public Criteria andPapertypeLessThanOrEqualTo(Integer value) {
            addCriterion("paperType <=", value, "papertype");
            return (Criteria) this;
        }

        public Criteria andPapertypeIn(List<Integer> values) {
            addCriterion("paperType in", values, "papertype");
            return (Criteria) this;
        }

        public Criteria andPapertypeNotIn(List<Integer> values) {
            addCriterion("paperType not in", values, "papertype");
            return (Criteria) this;
        }

        public Criteria andPapertypeBetween(Integer value1, Integer value2) {
            addCriterion("paperType between", value1, value2, "papertype");
            return (Criteria) this;
        }

        public Criteria andPapertypeNotBetween(Integer value1, Integer value2) {
            addCriterion("paperType not between", value1, value2, "papertype");
            return (Criteria) this;
        }

        public Criteria andPaperdeptIsNull() {
            addCriterion("paperDept is null");
            return (Criteria) this;
        }

        public Criteria andPaperdeptIsNotNull() {
            addCriterion("paperDept is not null");
            return (Criteria) this;
        }

        public Criteria andPaperdeptEqualTo(String value) {
            addCriterion("paperDept =", value, "paperdept");
            return (Criteria) this;
        }

        public Criteria andPaperdeptNotEqualTo(String value) {
            addCriterion("paperDept <>", value, "paperdept");
            return (Criteria) this;
        }

        public Criteria andPaperdeptGreaterThan(String value) {
            addCriterion("paperDept >", value, "paperdept");
            return (Criteria) this;
        }

        public Criteria andPaperdeptGreaterThanOrEqualTo(String value) {
            addCriterion("paperDept >=", value, "paperdept");
            return (Criteria) this;
        }

        public Criteria andPaperdeptLessThan(String value) {
            addCriterion("paperDept <", value, "paperdept");
            return (Criteria) this;
        }

        public Criteria andPaperdeptLessThanOrEqualTo(String value) {
            addCriterion("paperDept <=", value, "paperdept");
            return (Criteria) this;
        }

        public Criteria andPaperdeptLike(String value) {
            addCriterion("paperDept like", value, "paperdept");
            return (Criteria) this;
        }

        public Criteria andPaperdeptNotLike(String value) {
            addCriterion("paperDept not like", value, "paperdept");
            return (Criteria) this;
        }

        public Criteria andPaperdeptIn(List<String> values) {
            addCriterion("paperDept in", values, "paperdept");
            return (Criteria) this;
        }

        public Criteria andPaperdeptNotIn(List<String> values) {
            addCriterion("paperDept not in", values, "paperdept");
            return (Criteria) this;
        }

        public Criteria andPaperdeptBetween(String value1, String value2) {
            addCriterion("paperDept between", value1, value2, "paperdept");
            return (Criteria) this;
        }

        public Criteria andPaperdeptNotBetween(String value1, String value2) {
            addCriterion("paperDept not between", value1, value2, "paperdept");
            return (Criteria) this;
        }

        public Criteria andPaperdeptidIsNull() {
            addCriterion("paperDeptId is null");
            return (Criteria) this;
        }

        public Criteria andPaperdeptidIsNotNull() {
            addCriterion("paperDeptId is not null");
            return (Criteria) this;
        }

        public Criteria andPaperdeptidEqualTo(Integer value) {
            addCriterion("paperDeptId =", value, "paperdeptid");
            return (Criteria) this;
        }

        public Criteria andPaperdeptidNotEqualTo(Integer value) {
            addCriterion("paperDeptId <>", value, "paperdeptid");
            return (Criteria) this;
        }

        public Criteria andPaperdeptidGreaterThan(Integer value) {
            addCriterion("paperDeptId >", value, "paperdeptid");
            return (Criteria) this;
        }

        public Criteria andPaperdeptidGreaterThanOrEqualTo(Integer value) {
            addCriterion("paperDeptId >=", value, "paperdeptid");
            return (Criteria) this;
        }

        public Criteria andPaperdeptidLessThan(Integer value) {
            addCriterion("paperDeptId <", value, "paperdeptid");
            return (Criteria) this;
        }

        public Criteria andPaperdeptidLessThanOrEqualTo(Integer value) {
            addCriterion("paperDeptId <=", value, "paperdeptid");
            return (Criteria) this;
        }

        public Criteria andPaperdeptidIn(List<Integer> values) {
            addCriterion("paperDeptId in", values, "paperdeptid");
            return (Criteria) this;
        }

        public Criteria andPaperdeptidNotIn(List<Integer> values) {
            addCriterion("paperDeptId not in", values, "paperdeptid");
            return (Criteria) this;
        }

        public Criteria andPaperdeptidBetween(Integer value1, Integer value2) {
            addCriterion("paperDeptId between", value1, value2, "paperdeptid");
            return (Criteria) this;
        }

        public Criteria andPaperdeptidNotBetween(Integer value1, Integer value2) {
            addCriterion("paperDeptId not between", value1, value2, "paperdeptid");
            return (Criteria) this;
        }

        public Criteria andPaperlevelIsNull() {
            addCriterion("paperLevel is null");
            return (Criteria) this;
        }

        public Criteria andPaperlevelIsNotNull() {
            addCriterion("paperLevel is not null");
            return (Criteria) this;
        }

        public Criteria andPaperlevelEqualTo(Integer value) {
            addCriterion("paperLevel =", value, "paperlevel");
            return (Criteria) this;
        }

        public Criteria andPaperlevelNotEqualTo(Integer value) {
            addCriterion("paperLevel <>", value, "paperlevel");
            return (Criteria) this;
        }

        public Criteria andPaperlevelGreaterThan(Integer value) {
            addCriterion("paperLevel >", value, "paperlevel");
            return (Criteria) this;
        }

        public Criteria andPaperlevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("paperLevel >=", value, "paperlevel");
            return (Criteria) this;
        }

        public Criteria andPaperlevelLessThan(Integer value) {
            addCriterion("paperLevel <", value, "paperlevel");
            return (Criteria) this;
        }

        public Criteria andPaperlevelLessThanOrEqualTo(Integer value) {
            addCriterion("paperLevel <=", value, "paperlevel");
            return (Criteria) this;
        }

        public Criteria andPaperlevelIn(List<Integer> values) {
            addCriterion("paperLevel in", values, "paperlevel");
            return (Criteria) this;
        }

        public Criteria andPaperlevelNotIn(List<Integer> values) {
            addCriterion("paperLevel not in", values, "paperlevel");
            return (Criteria) this;
        }

        public Criteria andPaperlevelBetween(Integer value1, Integer value2) {
            addCriterion("paperLevel between", value1, value2, "paperlevel");
            return (Criteria) this;
        }

        public Criteria andPaperlevelNotBetween(Integer value1, Integer value2) {
            addCriterion("paperLevel not between", value1, value2, "paperlevel");
            return (Criteria) this;
        }

        public Criteria andPaperstatusIsNull() {
            addCriterion("paperStatus is null");
            return (Criteria) this;
        }

        public Criteria andPaperstatusIsNotNull() {
            addCriterion("paperStatus is not null");
            return (Criteria) this;
        }

        public Criteria andPaperstatusEqualTo(Integer value) {
            addCriterion("paperStatus =", value, "paperstatus");
            return (Criteria) this;
        }

        public Criteria andPaperstatusNotEqualTo(Integer value) {
            addCriterion("paperStatus <>", value, "paperstatus");
            return (Criteria) this;
        }

        public Criteria andPaperstatusGreaterThan(Integer value) {
            addCriterion("paperStatus >", value, "paperstatus");
            return (Criteria) this;
        }

        public Criteria andPaperstatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("paperStatus >=", value, "paperstatus");
            return (Criteria) this;
        }

        public Criteria andPaperstatusLessThan(Integer value) {
            addCriterion("paperStatus <", value, "paperstatus");
            return (Criteria) this;
        }

        public Criteria andPaperstatusLessThanOrEqualTo(Integer value) {
            addCriterion("paperStatus <=", value, "paperstatus");
            return (Criteria) this;
        }

        public Criteria andPaperstatusIn(List<Integer> values) {
            addCriterion("paperStatus in", values, "paperstatus");
            return (Criteria) this;
        }

        public Criteria andPaperstatusNotIn(List<Integer> values) {
            addCriterion("paperStatus not in", values, "paperstatus");
            return (Criteria) this;
        }

        public Criteria andPaperstatusBetween(Integer value1, Integer value2) {
            addCriterion("paperStatus between", value1, value2, "paperstatus");
            return (Criteria) this;
        }

        public Criteria andPaperstatusNotBetween(Integer value1, Integer value2) {
            addCriterion("paperStatus not between", value1, value2, "paperstatus");
            return (Criteria) this;
        }

        public Criteria andIsfirstfollowupIsNull() {
            addCriterion("isFirstFollowup is null");
            return (Criteria) this;
        }

        public Criteria andIsfirstfollowupIsNotNull() {
            addCriterion("isFirstFollowup is not null");
            return (Criteria) this;
        }

        public Criteria andIsfirstfollowupEqualTo(Integer value) {
            addCriterion("isFirstFollowup =", value, "isfirstfollowup");
            return (Criteria) this;
        }

        public Criteria andIsfirstfollowupNotEqualTo(Integer value) {
            addCriterion("isFirstFollowup <>", value, "isfirstfollowup");
            return (Criteria) this;
        }

        public Criteria andIsfirstfollowupGreaterThan(Integer value) {
            addCriterion("isFirstFollowup >", value, "isfirstfollowup");
            return (Criteria) this;
        }

        public Criteria andIsfirstfollowupGreaterThanOrEqualTo(Integer value) {
            addCriterion("isFirstFollowup >=", value, "isfirstfollowup");
            return (Criteria) this;
        }

        public Criteria andIsfirstfollowupLessThan(Integer value) {
            addCriterion("isFirstFollowup <", value, "isfirstfollowup");
            return (Criteria) this;
        }

        public Criteria andIsfirstfollowupLessThanOrEqualTo(Integer value) {
            addCriterion("isFirstFollowup <=", value, "isfirstfollowup");
            return (Criteria) this;
        }

        public Criteria andIsfirstfollowupIn(List<Integer> values) {
            addCriterion("isFirstFollowup in", values, "isfirstfollowup");
            return (Criteria) this;
        }

        public Criteria andIsfirstfollowupNotIn(List<Integer> values) {
            addCriterion("isFirstFollowup not in", values, "isfirstfollowup");
            return (Criteria) this;
        }

        public Criteria andIsfirstfollowupBetween(Integer value1, Integer value2) {
            addCriterion("isFirstFollowup between", value1, value2, "isfirstfollowup");
            return (Criteria) this;
        }

        public Criteria andIsfirstfollowupNotBetween(Integer value1, Integer value2) {
            addCriterion("isFirstFollowup not between", value1, value2, "isfirstfollowup");
            return (Criteria) this;
        }

        public Criteria andUsernameLikeInsensitive(String value) {
            addCriterion("upper(userName) like", value.toUpperCase(), "username");
            return (Criteria) this;
        }

        public Criteria andPapertileLikeInsensitive(String value) {
            addCriterion("upper(paperTile) like", value.toUpperCase(), "papertile");
            return (Criteria) this;
        }

        public Criteria andPapersummaryLikeInsensitive(String value) {
            addCriterion("upper(paperSummary) like", value.toUpperCase(), "papersummary");
            return (Criteria) this;
        }

        public Criteria andPaperbgLikeInsensitive(String value) {
            addCriterion("upper(paperBg) like", value.toUpperCase(), "paperbg");
            return (Criteria) this;
        }

        public Criteria andPaperdeptLikeInsensitive(String value) {
            addCriterion("upper(paperDept) like", value.toUpperCase(), "paperdept");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated do_not_delete_during_merge Fri Oct 14 15:36:19 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mb_paperstemplates
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}