package com.ezhuanbing.api.dao.mybatis.model;

import java.util.Date;

public class PapersTemplates {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_paperstemplates.id
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_paperstemplates.userName
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_paperstemplates.userNameId
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    private Integer usernameid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_paperstemplates.paperTile
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    private String papertile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_paperstemplates.paperSummary
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    private String papersummary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_paperstemplates.paperStartDate
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    private Date paperstartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_paperstemplates.paperBg
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    private String paperbg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_paperstemplates.paperType
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    private Integer papertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_paperstemplates.paperDept
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    private String paperdept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_paperstemplates.paperDeptId
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    private Integer paperdeptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_paperstemplates.paperLevel
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    private Integer paperlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_paperstemplates.paperStatus
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    private Integer paperstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_paperstemplates.isFirstFollowup
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    private Integer isfirstfollowup;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_paperstemplates.id
     *
     * @return the value of mb_paperstemplates.id
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_paperstemplates.id
     *
     * @param id the value for mb_paperstemplates.id
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_paperstemplates.userName
     *
     * @return the value of mb_paperstemplates.userName
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_paperstemplates.userName
     *
     * @param username the value for mb_paperstemplates.userName
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_paperstemplates.userNameId
     *
     * @return the value of mb_paperstemplates.userNameId
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public Integer getUsernameid() {
        return usernameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_paperstemplates.userNameId
     *
     * @param usernameid the value for mb_paperstemplates.userNameId
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public void setUsernameid(Integer usernameid) {
        this.usernameid = usernameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_paperstemplates.paperTile
     *
     * @return the value of mb_paperstemplates.paperTile
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public String getPapertile() {
        return papertile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_paperstemplates.paperTile
     *
     * @param papertile the value for mb_paperstemplates.paperTile
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public void setPapertile(String papertile) {
        this.papertile = papertile == null ? null : papertile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_paperstemplates.paperSummary
     *
     * @return the value of mb_paperstemplates.paperSummary
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public String getPapersummary() {
        return papersummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_paperstemplates.paperSummary
     *
     * @param papersummary the value for mb_paperstemplates.paperSummary
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public void setPapersummary(String papersummary) {
        this.papersummary = papersummary == null ? null : papersummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_paperstemplates.paperStartDate
     *
     * @return the value of mb_paperstemplates.paperStartDate
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public Date getPaperstartdate() {
        return paperstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_paperstemplates.paperStartDate
     *
     * @param paperstartdate the value for mb_paperstemplates.paperStartDate
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public void setPaperstartdate(Date paperstartdate) {
        this.paperstartdate = paperstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_paperstemplates.paperBg
     *
     * @return the value of mb_paperstemplates.paperBg
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public String getPaperbg() {
        return paperbg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_paperstemplates.paperBg
     *
     * @param paperbg the value for mb_paperstemplates.paperBg
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public void setPaperbg(String paperbg) {
        this.paperbg = paperbg == null ? null : paperbg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_paperstemplates.paperType
     *
     * @return the value of mb_paperstemplates.paperType
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public Integer getPapertype() {
        return papertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_paperstemplates.paperType
     *
     * @param papertype the value for mb_paperstemplates.paperType
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public void setPapertype(Integer papertype) {
        this.papertype = papertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_paperstemplates.paperDept
     *
     * @return the value of mb_paperstemplates.paperDept
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public String getPaperdept() {
        return paperdept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_paperstemplates.paperDept
     *
     * @param paperdept the value for mb_paperstemplates.paperDept
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public void setPaperdept(String paperdept) {
        this.paperdept = paperdept == null ? null : paperdept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_paperstemplates.paperDeptId
     *
     * @return the value of mb_paperstemplates.paperDeptId
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public Integer getPaperdeptid() {
        return paperdeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_paperstemplates.paperDeptId
     *
     * @param paperdeptid the value for mb_paperstemplates.paperDeptId
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public void setPaperdeptid(Integer paperdeptid) {
        this.paperdeptid = paperdeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_paperstemplates.paperLevel
     *
     * @return the value of mb_paperstemplates.paperLevel
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public Integer getPaperlevel() {
        return paperlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_paperstemplates.paperLevel
     *
     * @param paperlevel the value for mb_paperstemplates.paperLevel
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public void setPaperlevel(Integer paperlevel) {
        this.paperlevel = paperlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_paperstemplates.paperStatus
     *
     * @return the value of mb_paperstemplates.paperStatus
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public Integer getPaperstatus() {
        return paperstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_paperstemplates.paperStatus
     *
     * @param paperstatus the value for mb_paperstemplates.paperStatus
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public void setPaperstatus(Integer paperstatus) {
        this.paperstatus = paperstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_paperstemplates.isFirstFollowup
     *
     * @return the value of mb_paperstemplates.isFirstFollowup
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public Integer getIsfirstfollowup() {
        return isfirstfollowup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_paperstemplates.isFirstFollowup
     *
     * @param isfirstfollowup the value for mb_paperstemplates.isFirstFollowup
     *
     * @mbggenerated Fri Oct 14 15:36:19 CST 2016
     */
    public void setIsfirstfollowup(Integer isfirstfollowup) {
        this.isfirstfollowup = isfirstfollowup;
    }
}