package com.ezhuanbing.api.dao.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class QuestionsTemplatesCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_questionstemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_questionstemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_questionstemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_questionstemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_questionstemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_questionstemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public QuestionsTemplatesCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_questionstemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_questionstemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_questionstemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_questionstemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_questionstemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_questionstemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_questionstemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_questionstemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_questionstemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_questionstemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_questionstemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_questionstemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_questionstemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_questionstemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mb_questionstemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andContentclassicidIsNull() {
            addCriterion("contentClassicId is null");
            return (Criteria) this;
        }

        public Criteria andContentclassicidIsNotNull() {
            addCriterion("contentClassicId is not null");
            return (Criteria) this;
        }

        public Criteria andContentclassicidEqualTo(Integer value) {
            addCriterion("contentClassicId =", value, "contentclassicid");
            return (Criteria) this;
        }

        public Criteria andContentclassicidNotEqualTo(Integer value) {
            addCriterion("contentClassicId <>", value, "contentclassicid");
            return (Criteria) this;
        }

        public Criteria andContentclassicidGreaterThan(Integer value) {
            addCriterion("contentClassicId >", value, "contentclassicid");
            return (Criteria) this;
        }

        public Criteria andContentclassicidGreaterThanOrEqualTo(Integer value) {
            addCriterion("contentClassicId >=", value, "contentclassicid");
            return (Criteria) this;
        }

        public Criteria andContentclassicidLessThan(Integer value) {
            addCriterion("contentClassicId <", value, "contentclassicid");
            return (Criteria) this;
        }

        public Criteria andContentclassicidLessThanOrEqualTo(Integer value) {
            addCriterion("contentClassicId <=", value, "contentclassicid");
            return (Criteria) this;
        }

        public Criteria andContentclassicidIn(List<Integer> values) {
            addCriterion("contentClassicId in", values, "contentclassicid");
            return (Criteria) this;
        }

        public Criteria andContentclassicidNotIn(List<Integer> values) {
            addCriterion("contentClassicId not in", values, "contentclassicid");
            return (Criteria) this;
        }

        public Criteria andContentclassicidBetween(Integer value1, Integer value2) {
            addCriterion("contentClassicId between", value1, value2, "contentclassicid");
            return (Criteria) this;
        }

        public Criteria andContentclassicidNotBetween(Integer value1, Integer value2) {
            addCriterion("contentClassicId not between", value1, value2, "contentclassicid");
            return (Criteria) this;
        }

        public Criteria andQsttypeIsNull() {
            addCriterion("qstType is null");
            return (Criteria) this;
        }

        public Criteria andQsttypeIsNotNull() {
            addCriterion("qstType is not null");
            return (Criteria) this;
        }

        public Criteria andQsttypeEqualTo(Integer value) {
            addCriterion("qstType =", value, "qsttype");
            return (Criteria) this;
        }

        public Criteria andQsttypeNotEqualTo(Integer value) {
            addCriterion("qstType <>", value, "qsttype");
            return (Criteria) this;
        }

        public Criteria andQsttypeGreaterThan(Integer value) {
            addCriterion("qstType >", value, "qsttype");
            return (Criteria) this;
        }

        public Criteria andQsttypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("qstType >=", value, "qsttype");
            return (Criteria) this;
        }

        public Criteria andQsttypeLessThan(Integer value) {
            addCriterion("qstType <", value, "qsttype");
            return (Criteria) this;
        }

        public Criteria andQsttypeLessThanOrEqualTo(Integer value) {
            addCriterion("qstType <=", value, "qsttype");
            return (Criteria) this;
        }

        public Criteria andQsttypeIn(List<Integer> values) {
            addCriterion("qstType in", values, "qsttype");
            return (Criteria) this;
        }

        public Criteria andQsttypeNotIn(List<Integer> values) {
            addCriterion("qstType not in", values, "qsttype");
            return (Criteria) this;
        }

        public Criteria andQsttypeBetween(Integer value1, Integer value2) {
            addCriterion("qstType between", value1, value2, "qsttype");
            return (Criteria) this;
        }

        public Criteria andQsttypeNotBetween(Integer value1, Integer value2) {
            addCriterion("qstType not between", value1, value2, "qsttype");
            return (Criteria) this;
        }

        public Criteria andQsttitleIsNull() {
            addCriterion("qstTitle is null");
            return (Criteria) this;
        }

        public Criteria andQsttitleIsNotNull() {
            addCriterion("qstTitle is not null");
            return (Criteria) this;
        }

        public Criteria andQsttitleEqualTo(String value) {
            addCriterion("qstTitle =", value, "qsttitle");
            return (Criteria) this;
        }

        public Criteria andQsttitleNotEqualTo(String value) {
            addCriterion("qstTitle <>", value, "qsttitle");
            return (Criteria) this;
        }

        public Criteria andQsttitleGreaterThan(String value) {
            addCriterion("qstTitle >", value, "qsttitle");
            return (Criteria) this;
        }

        public Criteria andQsttitleGreaterThanOrEqualTo(String value) {
            addCriterion("qstTitle >=", value, "qsttitle");
            return (Criteria) this;
        }

        public Criteria andQsttitleLessThan(String value) {
            addCriterion("qstTitle <", value, "qsttitle");
            return (Criteria) this;
        }

        public Criteria andQsttitleLessThanOrEqualTo(String value) {
            addCriterion("qstTitle <=", value, "qsttitle");
            return (Criteria) this;
        }

        public Criteria andQsttitleLike(String value) {
            addCriterion("qstTitle like", value, "qsttitle");
            return (Criteria) this;
        }

        public Criteria andQsttitleNotLike(String value) {
            addCriterion("qstTitle not like", value, "qsttitle");
            return (Criteria) this;
        }

        public Criteria andQsttitleIn(List<String> values) {
            addCriterion("qstTitle in", values, "qsttitle");
            return (Criteria) this;
        }

        public Criteria andQsttitleNotIn(List<String> values) {
            addCriterion("qstTitle not in", values, "qsttitle");
            return (Criteria) this;
        }

        public Criteria andQsttitleBetween(String value1, String value2) {
            addCriterion("qstTitle between", value1, value2, "qsttitle");
            return (Criteria) this;
        }

        public Criteria andQsttitleNotBetween(String value1, String value2) {
            addCriterion("qstTitle not between", value1, value2, "qsttitle");
            return (Criteria) this;
        }

        public Criteria andQstpictureIsNull() {
            addCriterion("qstPicture is null");
            return (Criteria) this;
        }

        public Criteria andQstpictureIsNotNull() {
            addCriterion("qstPicture is not null");
            return (Criteria) this;
        }

        public Criteria andQstpictureEqualTo(String value) {
            addCriterion("qstPicture =", value, "qstpicture");
            return (Criteria) this;
        }

        public Criteria andQstpictureNotEqualTo(String value) {
            addCriterion("qstPicture <>", value, "qstpicture");
            return (Criteria) this;
        }

        public Criteria andQstpictureGreaterThan(String value) {
            addCriterion("qstPicture >", value, "qstpicture");
            return (Criteria) this;
        }

        public Criteria andQstpictureGreaterThanOrEqualTo(String value) {
            addCriterion("qstPicture >=", value, "qstpicture");
            return (Criteria) this;
        }

        public Criteria andQstpictureLessThan(String value) {
            addCriterion("qstPicture <", value, "qstpicture");
            return (Criteria) this;
        }

        public Criteria andQstpictureLessThanOrEqualTo(String value) {
            addCriterion("qstPicture <=", value, "qstpicture");
            return (Criteria) this;
        }

        public Criteria andQstpictureLike(String value) {
            addCriterion("qstPicture like", value, "qstpicture");
            return (Criteria) this;
        }

        public Criteria andQstpictureNotLike(String value) {
            addCriterion("qstPicture not like", value, "qstpicture");
            return (Criteria) this;
        }

        public Criteria andQstpictureIn(List<String> values) {
            addCriterion("qstPicture in", values, "qstpicture");
            return (Criteria) this;
        }

        public Criteria andQstpictureNotIn(List<String> values) {
            addCriterion("qstPicture not in", values, "qstpicture");
            return (Criteria) this;
        }

        public Criteria andQstpictureBetween(String value1, String value2) {
            addCriterion("qstPicture between", value1, value2, "qstpicture");
            return (Criteria) this;
        }

        public Criteria andQstpictureNotBetween(String value1, String value2) {
            addCriterion("qstPicture not between", value1, value2, "qstpicture");
            return (Criteria) this;
        }

        public Criteria andQstrestultcountIsNull() {
            addCriterion("qstRestultCount is null");
            return (Criteria) this;
        }

        public Criteria andQstrestultcountIsNotNull() {
            addCriterion("qstRestultCount is not null");
            return (Criteria) this;
        }

        public Criteria andQstrestultcountEqualTo(Integer value) {
            addCriterion("qstRestultCount =", value, "qstrestultcount");
            return (Criteria) this;
        }

        public Criteria andQstrestultcountNotEqualTo(Integer value) {
            addCriterion("qstRestultCount <>", value, "qstrestultcount");
            return (Criteria) this;
        }

        public Criteria andQstrestultcountGreaterThan(Integer value) {
            addCriterion("qstRestultCount >", value, "qstrestultcount");
            return (Criteria) this;
        }

        public Criteria andQstrestultcountGreaterThanOrEqualTo(Integer value) {
            addCriterion("qstRestultCount >=", value, "qstrestultcount");
            return (Criteria) this;
        }

        public Criteria andQstrestultcountLessThan(Integer value) {
            addCriterion("qstRestultCount <", value, "qstrestultcount");
            return (Criteria) this;
        }

        public Criteria andQstrestultcountLessThanOrEqualTo(Integer value) {
            addCriterion("qstRestultCount <=", value, "qstrestultcount");
            return (Criteria) this;
        }

        public Criteria andQstrestultcountIn(List<Integer> values) {
            addCriterion("qstRestultCount in", values, "qstrestultcount");
            return (Criteria) this;
        }

        public Criteria andQstrestultcountNotIn(List<Integer> values) {
            addCriterion("qstRestultCount not in", values, "qstrestultcount");
            return (Criteria) this;
        }

        public Criteria andQstrestultcountBetween(Integer value1, Integer value2) {
            addCriterion("qstRestultCount between", value1, value2, "qstrestultcount");
            return (Criteria) this;
        }

        public Criteria andQstrestultcountNotBetween(Integer value1, Integer value2) {
            addCriterion("qstRestultCount not between", value1, value2, "qstrestultcount");
            return (Criteria) this;
        }

        public Criteria andQsttitleLikeInsensitive(String value) {
            addCriterion("upper(qstTitle) like", value.toUpperCase(), "qsttitle");
            return (Criteria) this;
        }

        public Criteria andQstpictureLikeInsensitive(String value) {
            addCriterion("upper(qstPicture) like", value.toUpperCase(), "qstpicture");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mb_questionstemplates
     *
     * @mbggenerated do_not_delete_during_merge Tue Sep 06 17:31:57 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mb_questionstemplates
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}