package com.ezhuanbing.api.dao.mybatis.model;

public class QuestionsTemplates {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_questionstemplates.id
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_questionstemplates.contentClassicId
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    private Integer contentclassicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_questionstemplates.qstType
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    private Integer qsttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_questionstemplates.qstTitle
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    private String qsttitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_questionstemplates.qstPicture
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    private String qstpicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_questionstemplates.qstRestultCount
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    private Integer qstrestultcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_questionstemplates.id
     *
     * @return the value of mb_questionstemplates.id
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_questionstemplates.id
     *
     * @param id the value for mb_questionstemplates.id
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_questionstemplates.contentClassicId
     *
     * @return the value of mb_questionstemplates.contentClassicId
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public Integer getContentclassicid() {
        return contentclassicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_questionstemplates.contentClassicId
     *
     * @param contentclassicid the value for mb_questionstemplates.contentClassicId
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void setContentclassicid(Integer contentclassicid) {
        this.contentclassicid = contentclassicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_questionstemplates.qstType
     *
     * @return the value of mb_questionstemplates.qstType
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public Integer getQsttype() {
        return qsttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_questionstemplates.qstType
     *
     * @param qsttype the value for mb_questionstemplates.qstType
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void setQsttype(Integer qsttype) {
        this.qsttype = qsttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_questionstemplates.qstTitle
     *
     * @return the value of mb_questionstemplates.qstTitle
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public String getQsttitle() {
        return qsttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_questionstemplates.qstTitle
     *
     * @param qsttitle the value for mb_questionstemplates.qstTitle
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void setQsttitle(String qsttitle) {
        this.qsttitle = qsttitle == null ? null : qsttitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_questionstemplates.qstPicture
     *
     * @return the value of mb_questionstemplates.qstPicture
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public String getQstpicture() {
        return qstpicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_questionstemplates.qstPicture
     *
     * @param qstpicture the value for mb_questionstemplates.qstPicture
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void setQstpicture(String qstpicture) {
        this.qstpicture = qstpicture == null ? null : qstpicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_questionstemplates.qstRestultCount
     *
     * @return the value of mb_questionstemplates.qstRestultCount
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public Integer getQstrestultcount() {
        return qstrestultcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_questionstemplates.qstRestultCount
     *
     * @param qstrestultcount the value for mb_questionstemplates.qstRestultCount
     *
     * @mbggenerated Tue Sep 06 17:31:57 CST 2016
     */
    public void setQstrestultcount(Integer qstrestultcount) {
        this.qstrestultcount = qstrestultcount;
    }
}